### ISSUE TITLE
"editor variable unset" error for variables containing spaces

### ISSUE THREAD

**Issue by cryzed** [rmarquis/pacaur#637]
###### Version

`pacaur -v`

```
pacaur 4.7.0
```

###### Description

I'm getting a "editor variable unset" error when attempting to use pacaur, even though it is set. `EDITOR` and `VISUAL` are set to `subl3 --wait`. It works when simply setting those to `subl3` instead, however that is not what I want. You can probably fix this by only running `command -v` on the first part before a whitespace character to check if a valid editor variable is set.

###### Output

`pacaur --Syu`

```
:: editor variable unset
```

###### Debug output

`bash -x pacaur --Syu`

```
+ version=4.7.0
+ unset aur cleancache devel edit info installpkg foreign needed noconfirm nodeps noedit
+ unset operation pac pacQ pacS quiet rebuild refresh repo search selective upgrade
+ LC_COLLATE=C
+ TEXTDOMAIN=pacaur
+ TEXTDOMAINDIR=/usr/share/locale
+ [[ -n '' ]]
+ configdir=/etc/xdg/pacaur
+ userconfigdir=/home/cryzed/.config/pacaur
+ userpacmandir=/home/cryzed/.config/pacman
+ usercachedir=/home/cryzed/.cache/pacaur
+ [[ -r '' ]]
+ source /etc/makepkg.conf
++ DLAGENTS=('ftp::/usr/bin/curl -fC - --ftp-pasv --retry 3 --retry-delay 3 -o %o %u' 'http::/usr/bin/curl -fLC - --retry 3 --retry-delay 3 -o %o %u' 'https::/usr/bin/curl -fLC - --retry 3 --retry-delay 3 -o %o %u' 'rsync::/usr/bin/rsync --no-motd -z %u %o' 'scp::/usr/bin/scp -C %u %o')
++ VCSCLIENTS=('bzr::bzr' 'git::git' 'hg::mercurial' 'svn::subversion')
++ CARCH=x86_64
++ CHOST=x86_64-pc-linux-gnu
++ CPPFLAGS=-D_FORTIFY_SOURCE=2
++ CFLAGS='-march=native -O2 -pipe -fstack-protector-strong'
++ CXXFLAGS='-march=native -O2 -pipe -fstack-protector-strong'
++ LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro
+++ nproc
+++ nproc
+++ nproc
++ MAKEFLAGS=-j4
++ DEBUG_CFLAGS='-g -fvar-tracking-assignments'
++ DEBUG_CXXFLAGS='-g -fvar-tracking-assignments'
++ BUILDENV=(!distcc color !ccache check !sign)
++ OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !optipng !upx !debug)
++ INTEGRITY_CHECK=(md5)
++ STRIP_BINARIES=--strip-all
++ STRIP_SHARED=--strip-unneeded
++ STRIP_STATIC=--strip-debug
++ MAN_DIRS=({usr{,/local}{,/share},opt/*}/{man,info})
++ DOC_DIRS=(usr/{,local/}{,share/}{doc,gtk-doc} opt/*/{doc,gtk-doc})
++ PURGE_TARGETS=(usr/{,share}/info/dir .packlist *.pod)
++ PKGDEST=/mnt/sdb1/makepkg
++ COMPRESSGZ=(gzip -c -f -n)
++ COMPRESSBZ2=(bzip2 -c -f)
++ COMPRESSXZ=(xz -c -z -)
++ COMPRESSLRZ=(lrzip -q)
++ COMPRESSLZO=(lzop -q)
++ COMPRESSZ=(compress -c -f)
++ PKGEXT=.pkg.tar.xz
++ SRCEXT=.src.tar.gz
+ [[ -r /home/cryzed/.config/pacman/makepkg.conf ]]
+ [[ -r /home/cryzed/.makepkg.conf ]]
+ editor='subl3 --wait'
+ displaybuildfiles=diff
+ fallback=true
+ silent=false
+ sortby=popularity
+ sortorder=descending
+ sudoloop=true
+ pacmanbin=pacman
+ clonedir=/home/cryzed/.cache/pacaur
+ aururl=aur.archlinux.org
+ aurrpc='/rpc.php?type=info&v=5'
+ source /etc/xdg/pacaur/config
+ [[ -r /home/cryzed/.config/pacaur/config ]]
+ [[ ! -d /home/cryzed/.cache/pacaur ]]
+ declare -A jsoncache
+ trap Cancel INT
+ args=($@)
+ for i in "${args[@]}"
+ [[ --Syu =~ ^-[a-zA-Z0-9] ]]
+ count=0
+ [[ -n --Syu ]]
+ getopts sidmykufecqrahvxVDFQRSTUbglnoptw-: OPT
+ pacmanarg+=("-$OPT")
+ case "$OPT" in
+ case "$OPTARG" in
+ pacopts+=("--$OPTARG")
+ getopts sidmykufecqrahvxVDFQRSTUbglnoptw-: OPT
+ [[ -z '' ]]
+ break
++ grep '^Color' /etc/pacman.conf
+ [[ -n Color ]]
+ [[ '' != \n\e\v\e\r ]]
+ [[ '' = \a\l\w\a\y\s ]]
+ coweropts+=("--color=auto")
+ reset='\e[0m'
+ colorR='\e[1;31m'
+ colorG='\e[1;32m'
+ colorY='\e[1;33m'
+ colorB='\e[1;34m'
+ colorM='\e[1;35m'
+ colorC='\e[1;36m'
+ colorW='\e[1;39m'
+ pacmanarg=(${pacmanarg[@]/--/})
+ pacmanarg=(${pacmanarg[@]/-r/})
+ pacmanarg=(${pacmanarg[@]/-a/})
+ [[ '' = sync ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
++ command -v 'subl3 --wait'
+ [[ ! -n '' ]]
+ Note e '\e[1;39meditor\e[0m variable unset'
+ case "$1" in
+ echo -e '\e[1;31m::\e[0m \e[1;39meditor\e[0m variable unset'
:: editor variable unset
+ exit 1
```

**Comment by rmarquis** [comment]
Should be fixed in 3c53c43eee17446e2c9c31571b4b706e26daceff.

**Comment by xelra** [comment]
This also happens now, if the `$EDITOR` variable doesn't exist. I never had an `$EDITOR` variable, but after upgrading to `4.7.0` just now, I also get this error.

**Comment by rmarquis** [comment]
Have you tried the latest code with `pacaur-git`?

If editor isn't set in the config file, pacaur looks for `$VISUAL`, then `$EDITOR`, and eventually uses `vi` as fallback.

**Comment by cryzed** [comment]
I simply edited the PKGBUILD to point to the archive file of the latest commit, the issue seems to be resolved. Are you talking about `/etc/xdg/pacaur/config`? I never modified that backup file, hence I don't have any *.pacnew/*.pacsave files that I can find.

**Comment by xelra** [comment]
I've upgraded to `pacaur 4.7.0.1.g3c53c43`. The problem still remains. It doesn't fallback to vi anymore, if neither `$VISUAL` nor `$EDITOR` are set.

My config is mint. Everything is commented out to default values.

**Comment by cryzed** [comment]
I didn't test for the fallback specifically, since I've always had `$VISUAL` and/or `$EDITOR` set.

**Comment by xelra** [comment]
@cryzed Sorry for hijacking your issue. I just thought it fitted in here very well. Your problem with the spaces is resolved with the latest commit. This is just about the fallback not working anymore.

**Comment by rmarquis** [comment]
@xelra I cannot reproduce. Do you actually have `vi` present on the system? It's default on a new Arch install, but chance are that you got rid of it and replaced it with `vim`.

@cryzed Thanks for your feedback!

**Comment by xelra** [comment]
@rmarquis You're right. I didn't have vi installed, only vim. It's still odd. It worked (probably with vim), without any problem before I upgraded to `4.7.0`.

**Comment by oprypin** [comment]
I confirm the bug

```console
$ export VISUAL='kate -b'
$ pacaur -Syu
:: editor variable unset
$ export VISUAL='kate'
$ pacaur -Syu
:: Synchronizing package databases...
```

I also confirm that it's fixed in *pacaur-git*. Please make a release soon 👍

**Comment by rmarquis** [comment]
Version 4.7.1 released.

**Comment by japhir** [comment]
I might have done something wrong here, but I've removed the package (`pacman -Rns pacaur`), removed the archives, git pulled the update in the `~/.cache/pacaur/pacaur` directory and did `makepkg -si`. This successfully installs the new `4.7.1` version on my system, but I still get the error `:: editor variable unset`.

**Comment by koterpillar** [comment]
The fix doesn't work with my `EDITOR="emacsclient --alternate-editor emacs"`, here's the relevant output:

```
...
+ editor='emacsclient --alternate-editor emacs'
...
++ command -v 'emacsclient --alternate-editor'
+ [[ ! -n '' ]]
+ Note e '\e[1;39meditor\e[0m variable unset'
+ case "$1" in
+ echo -e '\e[1;31m::\e[0m \e[1;39meditor\e[0m variable unset'
:: editor variable unset
+ exit 1
```

**Comment by koterpillar** [comment]
In the linked commit (3c53c43eee17446e2c9c31571b4b706e26daceff), should `"${editor% *}"` be `"${editor%% *}"`?

**Comment by rmarquis** [comment]
Indeed (032fe0595fb103738fe01128f97494c04cd800a8). I'm not going to make a new release before a few days, please use pacaur-git in the meantime.

**Comment by corngood** [comment]
This editor check is breaking arch-travis (https://github.com/mikkeloscar/arch-travis/issues/21).  We can work around (either in arch-travis or client projects) it by setting `EDITOR=false`.

Do you think this should be considered a bug in pacaur?

**Comment by rmarquis** [comment]
@corngood: Not a bug in pacaur.

**Comment by mazulo** [comment]
@rmarquis I've using `pacaur 4.7.3`, and still getting this error. What else I have to do to fix this issue?

**Comment by nbars** [comment]
You need to put the `export EDITOR` statement into you shell initialization file (e.g. bashrc).

**Comment by ibrokemypie** [comment]
Exporting EDITOR did not work for me, had to export VISUAL to get the error to stop, which is a bit confusing due to what it says...

**Comment by mazulo** [comment]
I'm using `pacaur 4.7.6` and still having this problem.

**Comment by nbars** [comment]
You need to export the ```EDITOR``` or ```VISUAL``` variable. If non of these variables are present, pacaur falls back to vi. If you not set any of theses variables, how pacaur should know what editor it should use for editing PKGBUILD files?

So, there are two ways for fixing this _problem_:

1. Install vi and leave the variables unset or
2. Set one of theses variables inside you're shell initialization script

**Comment by Nelthorim** [comment]
This bug is still present in the latest git release:

```
nelthorim@maxwell ~ λ echo $EDITOR
emacsclient -t
nelthorim@maxwell ~ λ echo $VISUAL
emacsclient -t -a emacs
nelthorim@maxwell ~ λ pacaur -Syua
:: $VISUAL and $EDITOR environment variables not set or defined editor not found
```

**Comment by andreas-h** [comment]
Same problem here:

    $ echo $EDITOR                                                                                                                                                                    
    emacsclient.emacs --socket-name /tmp/emacs1000/server -t -a emacs -nw
    
    $ echo $VISUAL                                                                                                                                                                    
    emacsclient.emacs --socket-name /tmp/emacs1000/server -c -a emacs
    
    $ LANG=en_US.utf-8 pacaur -Ss samba                                                                                                                                               
    :: editor variable unset
    
    $ zsh --version                                                                                                                                                                   
    zsh 5.4.2 (x86_64-unknown-linux-gnu)
    
    $ pacaur --version                                                                                                                                                                
    pacaur 4.7.10
    
    $                                                       

When I use the pacaur-git package, the error message changes to

    :: $VISUAL and $EDITOR environment variables not set or defined editor not found

But `$VISUAL` and `$EDITOR` **are** defined ...

**Comment by rmarquis** [comment]
How did you define the variable?

**Comment by andreas-h** [comment]
I have the following in my `.zshenv`

    export EDITOR='emacsclient.emacs --socket-name /tmp/emacs1000/server -t -a emacs -nw'
    export VISUAL='emacsclient.emacs --socket-name /tmp/emacs1000/server -c -a emacs'

**Comment by andreas-h** [comment]
Sorry, stupid mistake on my side, as the `emacsclient.emacs` binary doesn't exist (sic!). Copied the file from another machine ...

So I can confirm that with the pacaur-git package, it works as advertised.

Sorry for the noise!
